'use client';
import { useMemo, useState } from 'react';
import { useT } from './i18n';
type MenuItem={id:string;name:string;description:string;price:number;icon:string;calories?:number;options?:string};
type Choice={name:string;price:number;kcal:number}; type Group={title:string;required?:boolean;multiple?:boolean;choices:Choice[]};
const money=(n:number)=>n.toLocaleString('ko-KR');
const choice=(name:string,price=0,kcal=0):Choice=>({name,price,kcal});
const one=(title:string,...choices:Choice[]):Group=>({title,required:true,choices});
const many=(title:string,...choices:Choice[]):Group=>({title,multiple:true,choices});

export function optionProfileForName(name:string):{id:string;groups:Group[]}{
  if(/무알코올/.test(name))return{id:'beverage',groups:[one('음료 상태',choice('차갑게'),choice('시원하지 않게')),many('추가 요청',choice('얼음컵',1000,0),choice('빨대 받기'))]};
  if(/소주|맥주|하이볼/.test(name))return{id:'adult-drink',groups:[one('음료 상태',choice('차갑게'),choice('시원하지 않게')),many('함께 주문',choice('얼음컵',1000,0),choice('레몬 슬라이스',500,5))]};
  if(/콜라|생수|식혜|유산균 음료|밀크티|리치 에이드/.test(name))return{id:'beverage',groups:[one('음료 상태',choice('차갑게'),choice('얼음 없이')),many('추가 요청',choice('얼음컵',1000,0),choice('빨대 받기'))]};
  if(/분식.*세트/.test(name))return{id:'snack-set',groups:[one('떡볶이 맵기',choice('순한맛'),choice('보통맛'),choice('매운맛')),one('세트 인원',choice('기본 구성'),choice('1인 추가',7000,650)),many('세트 추가',choice('모짜렐라 치즈',2500,220),choice('김말이 3개',2500,210),choice('어묵 국물',1000,40))]};
  if(/닭발/.test(name))return{id:'spicy-chicken-feet',groups:[one('맵기 선택',choice('덜 맵게'),choice('보통맛'),choice('아주 맵게')),one('조리 선택',choice('직화구이'),choice('국물 닭발',1000,80)),many('함께 먹기',choice('날치알 주먹밥',4500,430),choice('계란찜',4000,180),choice('누룽지탕',3500,210),choice('치즈 추가',2500,220))]};
  if(/오돌뼈/.test(name))return{id:'spicy-cartilage',groups:[one('맵기 선택',choice('덜 맵게'),choice('보통맛'),choice('아주 맵게')),one('구성 선택',choice('오돌뼈만'),choice('주먹밥 세트',4000,430)),many('추가 메뉴',choice('계란찜',4000,180),choice('치즈 추가',2500,220),choice('마요 소스',500,90))]};
  if(/보쌈/.test(name))return{id:'bossam',groups:[one('고기 양',choice('기본'),choice('고기 추가',7000,520)),one('김치 선택',choice('보쌈김치'),choice('무김치')),many('곁들임 추가',choice('막국수',7000,480),choice('쌈 채소',2000,35),choice('마늘·고추',1000,20),choice('공깃밥',1000,300))]};
  if(/오징어볶음/.test(name))return{id:'spicy-squid',groups:[one('맵기 선택',choice('덜 맵게'),choice('보통맛'),choice('매운맛')),one('구성 선택',choice('오징어볶음만'),choice('덮밥으로',1500,300)),many('추가 메뉴',choice('소면사리',2000,280),choice('계란후라이',1000,95),choice('공깃밥',1000,300))]};
  if(/골뱅이/.test(name))return{id:'spicy-whelk',groups:[one('맵기 선택',choice('덜 맵게'),choice('보통맛'),choice('매운맛')),one('소면 양',choice('기본'),choice('소면 추가',2000,280)),many('추가 메뉴',choice('오이 추가',1000,15),choice('쥐포튀김',4500,310))]};
  if(/해물찜/.test(name))return{id:'seafood-steam',groups:[one('맵기 선택',choice('순한맛'),choice('보통맛'),choice('매운맛')),one('양 선택',choice('2인'),choice('3인',9000,450)),many('사리 추가',choice('콩나물 추가',1500,35),choice('우동사리',2000,260),choice('볶음밥 재료',2500,320))]};
  if(/버터구이 오징어/.test(name))return{id:'grilled-squid',groups:[one('자르기',choice('통으로'),choice('먹기 좋게 자르기')),one('버터 양',choice('기본'),choice('버터 적게',0,-80)),many('소스 추가',choice('마요 소스',500,90),choice('매운 소스',500,45))]};
  if(/새우 소금구이/.test(name))return{id:'grilled-shrimp',groups:[one('양 선택',choice('기본'),choice('새우 추가',7000,210)),one('손질 선택',choice('껍질 그대로'),choice('머리 제거')),many('소스 추가',choice('초장'),choice('레몬 버터 소스',1000,110))]};
  if(/김치전/.test(name))return{id:'korean-pancake',groups:[one('크기 선택',choice('기본 1장'),choice('2장',12000,650)),one('굽기 선택',choice('기본'),choice('바삭하게')),many('곁들임',choice('양파간장'),choice('막걸리 대신 식혜',2500,120))]};
  if(/피자|페퍼로니/.test(name))return{id:'pizza',groups:[one('크기 선택',choice('M'),choice('L',5000,520)),one('도우 선택',choice('오리지널'),choice('씬 도우'),choice('치즈크러스트',3000,260)),many('토핑 추가',choice('치즈 추가',2500,220),choice('페퍼로니 추가',2500,170),choice('올리브 추가',1000,35),choice('갈릭디핑 소스',500,120))]};
  if(/오븐 스파게티/.test(name))return{id:'oven-pasta',groups:[one('맵기 선택',choice('기본'),choice('매콤하게')),one('치즈 양',choice('기본'),choice('치즈 추가',2000,220)),many('토핑 추가',choice('베이컨',1500,120),choice('버섯',1000,35))]};
  if(/버거/.test(name))return{id:'burger',groups:[one('구성 선택',choice('단품'),choice('감자튀김 세트',3500,420)),many('버거 옵션',choice('패티 추가',3000,260),choice('치즈 추가',800,70),choice('베이컨 추가',1200,90),choice('피클 제외')),many('음료 선택',choice('콜라',1500,210),choice('제로콜라',1500,0))]};
  if(/감자튀김/.test(name))return{id:'fries',groups:[one('사이즈',choice('Regular'),choice('Large',1500,230)),one('시즈닝',choice('기본 소금'),choice('치즈 시즈닝',500,45),choice('갈릭 시즈닝',500,35)),many('소스 추가',choice('케첩'),choice('치즈 소스',800,100),choice('갈릭 소스',800,120))]};
  if(/버팔로 윙/.test(name))return{id:'buffalo-wing',groups:[one('수량 선택',choice('8조각'),choice('16조각',8000,620)),one('맵기 선택',choice('순한맛'),choice('보통맛'),choice('매운맛')),many('소스 추가',choice('랜치 소스',800,120),choice('매운 소스',500,45))]};
  if(/어니언링|너겟/.test(name))return{id:'fried-snack',groups:[one('수량 선택',choice('기본'),choice('더블',3500,320)),many('소스 선택',choice('케첩'),choice('머스터드'),choice('치즈 소스',800,100))]};
  if(/치즈볼/.test(name))return{id:'cheese-ball',groups:[one('수량',choice('5개'),choice('10개',4000,360)),many('소스 추가',choice('치즈 시즈닝',500,45),choice('매콤 소스',500,40))]};
  if(/치킨|후라이드|양념|간장|윙|텐더/.test(name))return{id:'chicken',groups:[one('구성 선택',choice(/순살|윙|텐더/.test(name)?'메뉴 기본 구성':'뼈 치킨'),...(/순살|윙|텐더/.test(name)?[]:[choice('순살로 변경',2000,80)])),one('양 선택',choice('한 마리'),choice('한 마리 반',9000,780)),many('소스·사이드',choice('양념 소스',1000,95),choice('마늘간장 소스',1000,80),choice('치킨무 추가',500,8),choice('콜라 1.25L',2500,525))]};
  if(/떡볶이|라볶이/.test(name))return{id:'tteokbokki',groups:[one('맵기 선택',choice('순한맛'),choice('보통맛'),choice('매운맛')),one('떡 선택',choice('밀떡'),choice('쌀떡')),many('토핑 추가',choice('납작당면',1500,180),choice('모짜렐라 치즈',2500,220),choice('삶은 달걀 2개',1500,140),choice('어묵 추가',1500,130))]};
  if(/순대/.test(name))return{id:'sundae',groups:[one('부속 선택',choice('순대만'),choice('내장 섞기')),one('양 선택',choice('1인분'),choice('곱빼기',5000,520)),many('곁들임',choice('쌈장'),choice('소금'),choice('떡볶이 국물',500,60))]};
  if(/튀김|짜조/.test(name))return{id:'fried-side',groups:[one('수량 선택',choice('기본 구성'),choice('2개 추가',2500,210)),many('소스 선택',choice('간장 소스'),choice('칠리 소스',500,45),choice('떡볶이 국물',500,60))]};
  if(/만두/.test(name))return{id:'dumpling',groups:[one('조리 선택',choice('찐만두'),choice('군만두',500,80)),one('수량 선택',choice('6개'),choice('10개',3500,300)),many('소스 선택',choice('초간장'),choice('매운 소스',500,45))]};
  if(/김밥/.test(name))return{id:'gimbap',groups:[one('수량 선택',choice('1줄'),choice('2줄',4500,420)),many('재료 조절',choice('단무지 제외'),choice('우엉 제외'),choice('마요네즈 추가',500,90)),many('함께 먹기',choice('미니 라면',3500,360),choice('어묵 국물',1000,40))]};
  if(/쫄면/.test(name))return{id:'jjolmyeon',groups:[one('맵기 선택',choice('덜 맵게'),choice('보통맛'),choice('매운맛')),one('면 양',choice('기본'),choice('곱빼기',1500,260)),many('토핑 추가',choice('삶은 달걀',800,70),choice('만두 3개',2500,210))]};
  if(/어묵탕|조개탕|홍합탕/.test(name))return{id:'clear-soup',groups:[one('국물 간',choice('기본'),choice('싱겁게'),choice('칼칼하게')),many('재료 추가',choice('어묵 추가',2500,210),choice('우동사리',2000,260),choice('청양고추 추가'),choice('공깃밥',1000,300))]};
  if(/김치찌개|순두부|된장찌개|육개장|국밥|똠얌꿍|갈비탕/.test(name))return{id:'stew',groups:[one('맵기·간 선택',choice('순하게'),choice('보통'),choice('얼큰하게')),one('밥 선택',choice('공깃밥 포함'),choice('밥 제외',0,-300)),many('재료 추가',choice('두부 추가',1200,85),choice('고기 추가',3000,210),choice('라면사리',1500,380),choice('계란',800,70))]};
  if(/쌀국수|팟타이|분짜|볶음면/.test(name))return{id:'asian-noodle',groups:[one('면 양',choice('기본'),choice('면 추가',2000,250)),one('향신채 선택',choice('고수 제외'),choice('고수 기본'),choice('고수 많이')),many('재료 추가',choice('숙주 추가',1000,20),choice('새우 추가',3000,90),choice('고기 추가',3000,210),choice('칠리 소스'))]};
  if(/나시고렝|카오팟|루러우판|닭고기밥|새우 볶음밥/.test(name))return{id:'asian-rice',groups:[one('밥 양',choice('기본'),choice('밥 적게',0,-90),choice('곱빼기',1500,300)),one('향신채 선택',choice('고수 제외'),choice('고수 기본')),many('토핑 추가',choice('계란후라이',1000,95),choice('고기 추가',3000,210),choice('새우 추가',3000,90))]};
  if(/커리/.test(name))return{id:'curry',groups:[one('맵기 선택',choice('순한맛'),choice('보통맛'),choice('매운맛')),one('밥 양',choice('기본'),choice('곱빼기',1500,300)),many('토핑 추가',choice('계란후라이',1000,95),choice('새우 추가',3000,90),choice('치킨 추가',3500,230))]};
  if(/아메리카노|라테|라떼|커피|플랫 화이트|초콜릿 라테|카푸치노/.test(name))return{id:'coffee',groups:[one('온도',choice('ICE'),choice('HOT')),one('사이즈',choice('Regular'),choice('Large',700,70)),one('당도',choice('기본'),choice('덜 달게',0,-40),choice('시럽 없이',0,-80)),many('음료 옵션',choice('샷 추가',500,5),choice('두유로 변경',600,25),choice('휘핑 추가',700,110))]};
  if(/에이드|아이스티|콜드브루|레몬 티/.test(name))return{id:'cold-drink',groups:[one('온도',choice('ICE'),choice('HOT')),one('사이즈',choice('Regular'),choice('Large',700,70)),one('당도',choice('0% 시럽 없이',0,-100),choice('50% 덜 달게',0,-50),choice('100% 기본')),many('추가 선택',choice('얼음 적게'),choice('과육 추가',800,55))]};
  if(/케이크|쿠키|크루아상|크림 샌드/.test(name))return{id:'dessert',groups:[one('포장 선택',choice('개별 포장'),choice('선물 포장',1000,0)),one('데우기',choice('그대로'),choice('따뜻하게 데우기')),many('함께 담기',choice('아메리카노',3500,10),choice('우유',2000,130),choice('초 추가',500,0))]};
  if(/비빔밥|덮밥|불고기|제육|한상|정식|고등어구이|김치볶음밥/.test(name))return{id:'korean-meal',groups:[one('밥 양',choice('밥 적게',0,-90),choice('기본'),choice('밥 곱빼기',1000,300)),many('곁들임',choice('계란후라이',1000,95),choice('반찬 추가',1500,120),choice('국 추가',1500,80)),many('빼기 선택',choice('고추장 제외'),choice('김치 제외'))]};
  if(/계란말이/.test(name))return{id:'rolled-egg',groups:[one('크기 선택',choice('기본'),choice('대형',3000,260)),many('재료 추가',choice('치즈 추가',1500,120),choice('대파 제외'),choice('케첩'))]};
  if(/공깃밥|주먹밥/.test(name))return{id:'rice-side',groups:[one('수량 선택',choice('1개'),choice('2개',1000,300)),many('추가 선택',choice('김가루 추가',500,20),choice('날치알 추가',1000,45),choice('마요네즈 제외'))]};
  if(/통감자|콘치즈|코울슬로|갈릭디핑 소스|우동사리|제로 콜라/.test(name))return{id:'side-dish',groups:[one('수량 선택',choice('1개'),choice('2개',0,0)),many('포장 요청',choice('소스 별도'),choice('일회용 수저 받기'))]};
  return{id:'quantity-only',groups:[one('수량 선택',choice('1개'),choice('2개',0,0)),many('요청 선택',choice('일회용 수저 받기'),choice('덜 맵게'),choice('소스 별도 포장'))]};
}

export default function MenuOptionsModal({menu,onClose,onAdd}:{menu:MenuItem;onClose:()=>void;onAdd:(m:MenuItem)=>void}){const t=useT();const profile=useMemo(()=>optionProfileForName(menu.name),[menu.name]);const groups=profile.groups;const [selected,setSelected]=useState<Record<number,string[]>>(()=>Object.fromEntries(groups.map((g,i)=>[i,g.required?[g.choices[0].name]:[]])));const chosen=groups.flatMap((g,i)=>g.choices.filter(x=>(selected[i]??[]).includes(x.name)));const price=menu.price+chosen.reduce((n,x)=>n+x.price,0);const calories=Math.max(0,(menu.calories??Math.round(menu.price/14))+chosen.reduce((n,x)=>n+x.kcal,0));const toggle=(gi:number,name:string,multiple?:boolean)=>setSelected(v=>({...v,[gi]:multiple?(v[gi]??[]).includes(name)?v[gi].filter(x=>x!==name):[...(v[gi]??[]),name]:[name]}));return <div className="modal-backdrop"><section className="modal-sheet options-sheet" data-option-profile={profile.id}><div className="modal-handle"/><header><div><span>내 입맛대로 고르기</span><h2>{menu.icon} {t(menu.name)}</h2><p>{t(menu.description)}</p></div><button onClick={onClose}>×</button></header><div className="calorie-preview"><span>예상 열량</span><b>🔥 약 {money(calories)} kcal</b></div>{groups.map((g,gi)=><fieldset key={g.title}><legend>{t(g.title)} {g.multiple&&<small>{t('여러 개 가능')}</small>}</legend><div className={`option-grid ${g.choices.length===3?'three':'two'}`}>{g.choices.map(x=>{const on=(selected[gi]??[]).includes(x.name);return <button type="button" className={on?'selected':''} onClick={()=>toggle(gi,x.name,g.multiple)} key={x.name}><b>{on?'✓ ':''}{t(x.name)}</b><small>{x.price>0?`+${money(x.price)}원`:x.price<0?`${money(x.price)}원`:'추가 없음'}</small></button>})}</div></fieldset>)}<button className="submit-button" onClick={()=>onAdd({...menu,id:`${menu.id}-${crypto.randomUUID()}`,price,calories,options:chosen.map(x=>x.name).join(' · ')})}>{money(price)}원 · 장바구니 담기</button></section></div>}
