'use client';
import { useMemo, useState } from 'react';
type MenuItem={id:string;name:string;description:string;price:number;icon:string;calories?:number;options?:string};
type Choice={name:string;price:number;kcal:number}; type Group={title:string;required?:boolean;multiple?:boolean;choices:Choice[]};
const money=(n:number)=>n.toLocaleString('ko-KR');
function groupsFor({name}:MenuItem):Group[]{
  if(/치킨|윙|닭발/.test(name))return[{title:'맛 선택',required:true,choices:[{name:'오리지널',price:0,kcal:0},{name:'양념',price:1000,kcal:95},{name:'매콤양념',price:1000,kcal:80}]},{title:'사이드 추가',multiple:true,choices:[{name:'치즈볼 5개',price:4500,kcal:360},{name:'감자튀김',price:3500,kcal:310},{name:'치킨무 추가',price:500,kcal:8},{name:'콜라 1.25L',price:2500,kcal:525}]}];
  if(/떡볶이|순대|분식|어묵/.test(name))return[{title:'맵기 선택',required:true,choices:[{name:'순한맛',price:0,kcal:0},{name:'보통맛',price:0,kcal:0},{name:'매운맛',price:0,kcal:0}]},{title:'토핑 추가',multiple:true,choices:[{name:'납작당면',price:1500,kcal:180},{name:'모짜렐라 치즈',price:2500,kcal:220},{name:'삶은 달걀 2개',price:1500,kcal:140},{name:'튀김 모둠',price:4000,kcal:430}]}];
  if(/커피|라테|라떼|에이드/.test(name))return[{title:'온도',required:true,choices:[{name:'ICE',price:0,kcal:0},{name:'HOT',price:0,kcal:0}]},{title:'사이즈',required:true,choices:[{name:'Regular',price:0,kcal:0},{name:'Large',price:700,kcal:70}]},{title:'음료 옵션',multiple:true,choices:[{name:'샷 추가',price:500,kcal:5},{name:'시럽 추가',price:500,kcal:60},{name:'두유로 변경',price:600,kcal:25},{name:'휘핑 추가',price:700,kcal:110}]}];
  if(/찌개|탕|국|똠얌/.test(name))return[{title:'맵기 선택',required:true,choices:[{name:'순한맛',price:0,kcal:0},{name:'보통맛',price:0,kcal:0},{name:'얼큰하게',price:0,kcal:0}]},{title:'재료 추가',multiple:true,choices:[{name:'두부 추가',price:1200,kcal:85},{name:'고기 추가',price:3000,kcal:210},{name:'라면사리',price:1500,kcal:380},{name:'공깃밥',price:1000,kcal:300}]}];
  if(/밥|비빔밥|불고기|보쌈/.test(name))return[{title:'밥 양',required:true,choices:[{name:'밥 적게',price:0,kcal:-90},{name:'기본',price:0,kcal:0},{name:'밥 곱빼기',price:1000,kcal:300}]},{title:'곁들임',multiple:true,choices:[{name:'계란후라이',price:1000,kcal:95},{name:'고기 추가',price:3000,kcal:210},{name:'반찬 추가',price:1500,kcal:120}]}];
  if(/케이크|디저트/.test(name))return[{title:'포장 선택',required:true,choices:[{name:'일반 포장',price:0,kcal:0},{name:'초 추가',price:500,kcal:0}]},{title:'함께 담기',multiple:true,choices:[{name:'아메리카노',price:3500,kcal:10},{name:'우유',price:2000,kcal:130}]}];
  if(/팟타이|면|당면/.test(name))return[{title:'맵기 선택',required:true,choices:[{name:'순한맛',price:0,kcal:0},{name:'보통맛',price:0,kcal:0},{name:'매운맛',price:0,kcal:0}]},{title:'재료 추가',multiple:true,choices:[{name:'면 추가',price:2000,kcal:250},{name:'새우 추가',price:3000,kcal:90},{name:'숙주 추가',price:1000,kcal:20},{name:'고수 추가',price:0,kcal:3}]}];
  return[{title:'양 선택',required:true,choices:[{name:'기본',price:0,kcal:0},{name:'곱빼기',price:1800,kcal:250}]},{title:'추가 선택',multiple:true,choices:[{name:'채소 추가',price:900,kcal:35},{name:'곁들임 추가',price:1800,kcal:190}]}];
}
export default function MenuOptionsModal({menu,onClose,onAdd}:{menu:MenuItem;onClose:()=>void;onAdd:(m:MenuItem)=>void}){const groups=useMemo(()=>groupsFor(menu),[menu]);const [selected,setSelected]=useState<Record<number,string[]>>(()=>Object.fromEntries(groups.map((g,i)=>[i,g.required?[g.choices[0].name]:[]])));const chosen=groups.flatMap((g,i)=>g.choices.filter(x=>(selected[i]??[]).includes(x.name)));const price=menu.price+chosen.reduce((n,x)=>n+x.price,0);const calories=Math.max(0,(menu.calories??Math.round(menu.price/14))+chosen.reduce((n,x)=>n+x.kcal,0));const toggle=(gi:number,name:string,multiple?:boolean)=>setSelected(v=>({...v,[gi]:multiple?(v[gi]??[]).includes(name)?v[gi].filter(x=>x!==name):[...(v[gi]??[]),name]:[name]}));return <div className="modal-backdrop"><section className="modal-sheet options-sheet"><div className="modal-handle"/><header><div><span>내 입맛대로 고르기</span><h2>{menu.icon} {menu.name}</h2><p>{menu.description}</p></div><button onClick={onClose}>×</button></header><div className="calorie-preview"><span>예상 열량</span><b>🔥 약 {money(calories)} kcal</b></div>{groups.map((g,gi)=><fieldset key={g.title}><legend>{g.title} {g.multiple&&<small>여러 개 가능</small>}</legend><div className={`option-grid ${g.choices.length===3?'three':'two'}`}>{g.choices.map(x=>{const on=(selected[gi]??[]).includes(x.name);return <button type="button" className={on?'selected':''} onClick={()=>toggle(gi,x.name,g.multiple)} key={x.name}><b>{on?'✓ ':''}{x.name}</b><small>{x.price?`+${money(x.price)}원`:'추가 없음'}</small></button>})}</div></fieldset>)}<button className="submit-button" onClick={()=>onAdd({...menu,id:`${menu.id}-${crypto.randomUUID()}`,price,calories,options:chosen.map(x=>x.name).join(' · ')})}>{money(price)}원 · 장바구니 담기</button></section></div>}
